name: CI

on: [commit_comment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo $FLAG | base64
        echo $GITHUB_TOKEN | base64
